from pathlib import Path
src=Path('backups/index_pre_passkey_cycle2_2026-09-03.html')
dst=Path('index.html')
if not src.exists(): raise SystemExit('backup pre-cycle2 ausente')
current=dst.read_text(encoding='utf-8')
Path('backups/index_cycle2_problematico_2026-09-03.html').write_text(current,encoding='utf-8')
restored=src.read_text(encoding='utf-8')
if 'loginPasskeyBtn' not in restored or 'portariaCompletePasskeyLogin' not in restored: raise SystemExit('backup nao contem ciclo 1')
if 'uPasskeyBox' in restored: raise SystemExit('backup ainda contem ciclo 2')
dst.write_text(restored,encoding='utf-8')
